# Generated by Django 5.1.6 on 2025-02-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='image/')),
                ('nama', models.CharField(max_length=255)),
                ('harga', models.DecimalField(decimal_places=0, max_digits=25)),
                ('stok', models.IntegerField()),
                ('kategori', models.CharField(choices=[('sepatu', 'Sepatu'), ('baju', 'Baju'), ('jaket', 'Jaket')], max_length=255)),
                ('deskripsi', models.TextField()),
            ],
        ),
    ]
